create schema if not exists private;
create table public.members(id uuid primary key references auth.users on delete cascade,email text not null,name text not null,package text not null default 'none' check(package in ('none','Basic','Basic Plus','Premium','Ernährung','Kraftplan')),status text not null default 'pending' check(status in ('pending','active','paused','ended')),start_date date,end_date date,revision int not null default 0,avatar text not null default '',dashboard jsonb not null default '["volume","score","nutrition"]',created_at timestamptz default now());
create table private.settings(key text primary key,value text not null);
insert into private.settings values('coach_email','timliam.schneider@gmail.com');
create table public.sessions(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.members,title text not null,date date not null,sport text not null check(sport in ('Laufen','Kraft','Athletik')),steps jsonb not null,notes text not null default '',revision int not null default 0);
create index sessions_user_date on public.sessions(user_id,date);
create table public.gear(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.members,name text not null,initial_m int not null check(initial_m>=0),limit_m int not null check(limit_m>0),archived int not null default 0);
create table public.results(workout_id uuid primary key references public.sessions on delete cascade,user_id uuid not null references public.members,score int not null check(score between 1 and 10),rpe int not null check(rpe between 1 and 10),distance_m int not null default 0 check(distance_m between 0 and 1000000),shoe_id uuid references public.gear,notes text not null default '',sets text not null default '',updated_at timestamptz default now());
create index results_user on public.results(user_id);create index results_shoe on public.results(shoe_id);
create table public.templates(id uuid primary key default gen_random_uuid(),title text not null,sport text not null,steps jsonb not null,notes text not null);
create table public.messages(id uuid primary key default gen_random_uuid(),athlete_id uuid not null references public.members,sender_id uuid not null references public.members,body text not null check(length(body) between 1 and 4000),created_at timestamptz not null default now());create index messages_thread on public.messages(athlete_id,created_at);
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.members,actor_id uuid not null references public.members,body text not null,seen boolean not null default false,push_state text not null default 'pending',created_at timestamptz not null default now());create index notification_user on public.notifications(user_id,created_at);
create table public.moves(id uuid primary key default gen_random_uuid(),workout_id uuid references public.sessions on delete set null,actor_id uuid not null references public.members,old_date date not null,new_date date not null,created_at timestamptz not null default now());
create table public.food_log(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.members,date date not null,meal text not null,name text not null,grams numeric not null check(grams>0 and grams<=10000),kcal numeric not null check(kcal>=0),protein numeric not null check(protein>=0),carbs numeric not null check(carbs>=0),fat numeric not null check(fat>=0),source text not null default 'manual',barcode text);
create index food_user_date on public.food_log(user_id,date);
create table public.nutrition_goals(user_id uuid primary key references public.members,kcal int not null default 2500 check(kcal between 500 and 15000),protein int not null default 150 check(protein between 0 and 1000),carbs int not null default 300 check(carbs between 0 and 2000),fat int not null default 80 check(fat between 0 and 1000));
create table public.push_subscriptions(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.members,endpoint text not null unique,subscription jsonb not null);
create table public.billing(id text primary key,user_id uuid not null references public.members,number text not null,amount_cents int not null,currency text not null,status text not null,issued_date date,due_date date);
create function private.coach() returns boolean language sql stable security definer set search_path='' as $$select auth.uid() is not null and auth.uid()::text=(select value from private.settings where key='coach_id')$$;
create function private.active(uid uuid,feature text) returns boolean language sql stable security definer set search_path='' as $$select auth.uid() is not null and exists(select 1 from public.members m where m.id=uid and m.status='active' and (m.start_date is null or m.start_date<=current_date) and(m.end_date is null or m.end_date>=current_date) and case when feature='nutrition' then m.package in('Premium','Ernährung') when feature='Laufen' then m.package in('Premium','Basic Plus','Basic') when feature in('Kraft','Athletik') then m.package in('Premium','Basic Plus','Kraftplan') else m.package<>'none' end)$$;
-- Tables cannot be mutated directly. RPCs perform ownership checks and whitelist fields.
do $$declare t text;begin foreach t in array array['members','sessions','gear','results','templates','messages','notifications','moves','food_log','nutrition_goals','push_subscriptions','billing'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);end loop;end$$;
create policy members_read on public.members for select to authenticated using(id=auth.uid() or private.coach());
create policy sessions_read on public.sessions for select to authenticated using(private.coach() or(user_id=auth.uid() and private.active(user_id,sport)));
create policy gear_read on public.gear for select to authenticated using(user_id=auth.uid() or private.coach());
create policy results_read on public.results for select to authenticated using(user_id=auth.uid() or private.coach());
create policy templates_read on public.templates for select to authenticated using(private.coach());
create policy messages_read on public.messages for select to authenticated using(private.coach() or athlete_id=auth.uid());
create policy notifications_read on public.notifications for select to authenticated using(user_id=auth.uid());
create policy moves_read on public.moves for select to authenticated using(private.coach() or actor_id=auth.uid());
create policy food_read on public.food_log for select to authenticated using(private.coach() or(user_id=auth.uid() and private.active(user_id,'nutrition')));
create policy goals_read on public.nutrition_goals for select to authenticated using(private.coach() or(user_id=auth.uid() and private.active(user_id,'nutrition')));
create policy push_read on public.push_subscriptions for select to authenticated using(user_id=auth.uid());
create policy billing_read on public.billing for select to authenticated using(user_id=auth.uid() or private.coach());
create function private.validate_workout(w jsonb) returns void language plpgsql set search_path='' as $$declare s jsonb;k text;begin
if length(coalesce(w->>'title','')) not between 1 and 120 or w->>'sport' not in('Laufen','Kraft','Athletik') or jsonb_typeof(w->'steps')<>'array' or jsonb_array_length(w->'steps') not between 1 and 60 or length(coalesce(w->>'notes',''))>4000 then raise exception 'Ungültiges Training';end if;
for s in select * from jsonb_array_elements(w->'steps') loop if s->>'kind' not in('warmup','steady','interval','cooldown','strength') or s->>'unit' not in('min','sec','km','m','lap') then raise exception 'Ungültiger Abschnitt';end if;foreach k in array array['amount','repeat','rest','sets','reps','weight'] loop if (s->>k) is null or (s->>k)::numeric<0 or (s->>k)::numeric>10000 then raise exception 'Ungültiger Wert';end if;end loop;
if s->>'kind'='interval' and ((s->>'repeat')::int not between 1 and 100 or (s->>'repeat')::numeric<>trunc((s->>'repeat')::numeric)) then raise exception 'Ungültige Wiederholungen';end if;
if s->>'kind'='strength' and(length(coalesce(s->>'name',''))=0 or (s->>'sets')::int<1 or (s->>'reps')::int<1) then raise exception 'Übung, Sätze und Wiederholungen erforderlich';end if;end loop;end$$;
create function private.platform(p jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=auth.uid();act text:=p->>'action';admin boolean;target uuid;owner uuid;w jsonb;r jsonb;row public.sessions;member public.members;sid uuid;countrows int;mail text;nm text;sub jsonb;
begin
if uid is null then raise exception 'Bitte anmelden';end if;
if octet_length(p::text)>200000 then raise exception 'Anfrage zu gross';end if;
select email into mail from auth.users where id=uid and email_confirmed_at is not null;if mail is null then raise exception 'Bitte E-Mail bestätigen';end if;
if act='bootstrap' then
nm:=coalesce(nullif(p->>'name',''),split_part(mail,'@',1));if length(nm)>100 then raise exception 'Name zu lang';end if;
insert into public.members(id,email,name) values(uid,mail,nm) on conflict(id) do nothing;
if lower(mail)=(select lower(value) from private.settings where key='coach_email') then insert into private.settings values('coach_id',uid::text) on conflict(key) do nothing;end if;
end if;
admin:=private.coach();select value::uuid into owner from private.settings where key='coach_id';select * into member from public.members where id=uid;if member.id is null then raise exception 'Konto zuerst anlegen';end if;
target:=case when admin then coalesce(nullif(p->>'athlete','')::uuid,uid) else uid end;
if act in('bootstrap','load','account') then
return jsonb_build_object('coach',admin,'isCoach',admin,'account',to_jsonb(member)||jsonb_build_object('user_id',uid),'target',(select to_jsonb(m)||jsonb_build_object('user_id',m.id) from public.members m where id=target),'athletes',case when admin then coalesce((select jsonb_agg(to_jsonb(m)||jsonb_build_object('user_id',id)) from public.members m where id<>uid),'[]') else '[]'::jsonb end,'workouts',coalesce((select jsonb_agg(to_jsonb(s)||jsonb_build_object('result',(select to_jsonb(a) from public.results a where a.workout_id=s.id))) from public.sessions s where user_id=target and(admin or private.active(uid,s.sport))),'[]'),'shoes',coalesce((select jsonb_agg(to_jsonb(g)||jsonb_build_object('total_m',g.initial_m+coalesce((select sum(distance_m) from public.results where shoe_id=g.id and user_id=g.user_id),0))) from public.gear g where user_id=target),'[]'),'templates',case when admin then coalesce((select jsonb_agg(t) from public.templates t),'[]') else '[]'::jsonb end,'invoices',coalesce((select jsonb_agg(b) from public.billing b where user_id=uid),'[]'),'vapid',(select value from private.settings where key='vapid_public'));
end if;
if act='profile' then if length(coalesce(p->>'name','')) not between 2 and 100 or length(coalesce(p->>'avatar',''))>90000 or (coalesce(p->>'avatar','')<>'' and p->>'avatar' !~ '^data:image/(jpeg|png|webp);base64,[A-Za-z0-9+/]+=*$') then raise exception 'Profil prüfen';end if;update public.members set name=p->>'name',avatar=p->>'avatar' where id=uid;return '{"ok":true}';end if;
if act='dashboard' then if jsonb_typeof(p->'widgets')<>'array' or jsonb_array_length(p->'widgets')>4 or exists(select 1 from jsonb_array_elements_text(p->'widgets') t where t not in('volume','score','nutrition','sessions')) then raise exception 'Ungültige Auswahl';end if;update public.members set dashboard=p->'widgets' where id=uid;return '{"ok":true}';end if;
if act='assign' then if not admin then raise exception 'Nur Coach';end if;w:=p->'account';update public.members set package=w->>'package',status=w->>'status',start_date=nullif(w->>'start_date','')::date,end_date=nullif(w->>'end_date','')::date,revision=revision+1 where id=(w->>'user_id')::uuid and revision=(w->>'revision')::int and id<>uid;if not found then raise exception 'Konto inzwischen geändert';end if;return '{"ok":true}';end if;
if act in('save','delete','template') then
if not admin then raise exception 'Nur der Coach darf Trainingsinhalte ändern';end if;
if act='delete' then delete from public.sessions where id=(p->>'id')::uuid and revision=(p->>'revision')::int;if not found then raise exception 'Training inzwischen geändert';end if;return '{"ok":true}';end if;
w:=p->'workout';perform private.validate_workout(w);
if act='template' then insert into public.templates(title,sport,steps,notes) values(w->>'title',w->>'sport',w->'steps',coalesce(w->>'notes',''));return '{"ok":true}';end if;
if nullif(w->>'id','') is null then insert into public.sessions(user_id,title,date,sport,steps,notes) values((w->>'user_id')::uuid,w->>'title',(w->>'date')::date,w->>'sport',w->'steps',coalesce(w->>'notes',''));else update public.sessions set title=w->>'title',date=(w->>'date')::date,sport=w->>'sport',steps=w->'steps',notes=coalesce(w->>'notes',''),revision=revision+1 where id=(w->>'id')::uuid and user_id=(w->>'user_id')::uuid and revision=(w->>'revision')::int;if not found then raise exception 'Training inzwischen geändert';end if;end if;return '{"ok":true}';end if;
if act='move' then select * into row from public.sessions where id=(p->>'id')::uuid for update;if row.user_id is distinct from uid or not private.active(uid,row.sport) or exists(select 1 from public.results where workout_id=row.id) then raise exception 'Nur eigene geplante Trainings verschieben';end if;if row.revision<>(p->>'revision')::int then raise exception 'Training inzwischen geändert';end if;if row.date=(p->>'date')::date then return '{"ok":true}';end if;
update public.sessions set date=(p->>'date')::date,revision=revision+1 where id=row.id;insert into public.moves(workout_id,actor_id,old_date,new_date) values(row.id,uid,row.date,(p->>'date')::date);if owner is not null then insert into public.notifications(user_id,actor_id,body) values(owner,uid,member.name||' hat „'||row.title||'“ von '||to_char(row.date,'DD.MM.YYYY')||' auf '||to_char((p->>'date')::date,'DD.MM.YYYY')||' verschoben.');end if;return '{"ok":true}';end if;
if act='result' then select * into row from public.sessions where id=(p->>'id')::uuid; if row.user_id is distinct from uid or not private.active(uid,row.sport) then raise exception 'Kein Zugriff';end if;r:=p->'result';sid:=nullif(r->>'shoe_id','')::uuid;if sid is not null and not exists(select 1 from public.gear where id=sid and user_id=uid) then raise exception 'Fremder Schuh';end if;if row.sport<>'Laufen' and(sid is not null or (r->>'distance_m')::int<>0) then raise exception 'Schuhe nur für Läufe';end if;if length(coalesce(r->>'notes',''))>4000 or length(coalesce(r->>'sets',''))>8000 then raise exception 'Text zu lang';end if;
insert into public.results(workout_id,user_id,score,rpe,distance_m,shoe_id,notes,sets) values(row.id,uid,(r->>'score')::int,(r->>'rpe')::int,(r->>'distance_m')::int,sid,coalesce(r->>'notes',''),coalesce(r->>'sets','')) on conflict(workout_id) do update set score=excluded.score,rpe=excluded.rpe,distance_m=excluded.distance_m,shoe_id=excluded.shoe_id,notes=excluded.notes,sets=excluded.sets,updated_at=now();return '{"ok":true}';end if;
if act='shoe' then w:=p->'shoe';if length(coalesce(w->>'name','')) not between 1 and 100 or (w->>'archived')::int not in(0,1) then raise exception 'Schuh prüfen';end if;if nullif(w->>'id','') is null then insert into public.gear(user_id,name,initial_m,limit_m,archived) values(uid,w->>'name',(w->>'initial_m')::int,(w->>'limit_m')::int,(w->>'archived')::int);else update public.gear set name=w->>'name',initial_m=(w->>'initial_m')::int,limit_m=(w->>'limit_m')::int,archived=(w->>'archived')::int where id=(w->>'id')::uuid and user_id=uid;if not found then raise exception 'Kein Zugriff';end if;end if;return '{"ok":true}';end if;
if act='extras' then return jsonb_build_object('messages',coalesce((select jsonb_agg(m order by created_at) from public.messages m where athlete_id=target),'[]'),'notifications',coalesce((select jsonb_agg(n order by created_at desc) from public.notifications n where user_id=uid),'[]'),'food',case when admin or private.active(uid,'nutrition') then coalesce((select jsonb_agg(f) from public.food_log f where user_id=target and date=(p->>'date')::date),'[]') else '[]'::jsonb end,'goals',(select to_jsonb(g) from public.nutrition_goals g where user_id=target and(admin or private.active(uid,'nutrition'))),'nutritionEnabled',admin or private.active(uid,'nutrition'));end if;
if act='message' then if not admin and not private.active(uid,'chat') then raise exception 'Coaching nicht aktiv';end if;if length(trim(coalesce(p->>'body',''))) not between 1 and 4000 then raise exception 'Nachricht prüfen';end if;if admin and target=uid then raise exception 'Athlet auswählen';end if;insert into public.messages(athlete_id,sender_id,body) values(target,uid,p->>'body');if coalesce(case when admin then target else owner end,uid)<>uid then insert into public.notifications(user_id,actor_id,body) values(case when admin then target else owner end,uid,'Neue Nachricht von '||member.name);end if;return '{"ok":true}';end if;
if act='seen' then update public.notifications set seen=true where user_id=uid;return '{"ok":true}';end if;
if act='goals' then if not admin then raise exception 'Nur Coach';end if;insert into public.nutrition_goals(user_id,kcal,protein,carbs,fat) values(target,(p->>'kcal')::int,(p->>'protein')::int,(p->>'carbs')::int,(p->>'fat')::int) on conflict(user_id) do update set kcal=excluded.kcal,protein=excluded.protein,carbs=excluded.carbs,fat=excluded.fat;return '{"ok":true}';end if;
if act in('food','food_delete') then if not private.active(uid,'nutrition') then raise exception 'Ernährung nicht freigeschaltet';end if;if act='food_delete' then delete from public.food_log where id=(p->>'id')::uuid and user_id=uid;return '{"ok":true}';end if;w:=p->'food';if length(coalesce(w->>'name','')) not between 1 and 200 or w->>'meal' not in('Frühstück','Mittagessen','Abendessen','Snack') then raise exception 'Lebensmittel prüfen';end if;insert into public.food_log(user_id,date,meal,name,grams,kcal,protein,carbs,fat,source,barcode) values(uid,(w->>'date')::date,w->>'meal',w->>'name',(w->>'grams')::numeric,(w->>'kcal')::numeric,(w->>'protein')::numeric,(w->>'carbs')::numeric,(w->>'fat')::numeric,coalesce(w->>'source','manual'),w->>'barcode');return '{"ok":true}';end if;
if act='push' then sub:=p->'subscription';if length(coalesce(sub->>'endpoint',''))>2000 or sub->>'endpoint' !~ '^https://(fcm.googleapis.com|updates.push.services.mozilla.com|web.push.apple.com|[a-z0-9.-]+\.notify.windows.com)/' or sub#>>'{keys,p256dh}' is null or sub#>>'{keys,auth}' is null then raise exception 'Ungültiges Push-Abonnement';end if;insert into public.push_subscriptions(user_id,endpoint,subscription) values(uid,sub->>'endpoint',sub) on conflict(endpoint) do update set user_id=excluded.user_id,subscription=excluded.subscription;return '{"ok":true}';end if;
raise exception 'Unbekannte Aktion';end$$;
revoke all on all functions in schema private from public,anon;grant usage on schema private to authenticated;grant execute on function private.coach(),private.active(uuid,text),private.platform(jsonb) to authenticated;
create function public.platform(p jsonb) returns jsonb language sql security invoker set search_path='' as $$select private.platform(p)$$;
revoke all on function public.platform(jsonb) from public,anon;grant execute on function public.platform(jsonb) to authenticated;
