export type Step={kind:'warmup'|'steady'|'interval'|'cooldown'|'strength';name:string;amount:number;unit:'min'|'sec'|'km'|'m'|'lap';target:string;repeat:number;rest:number;restTarget:string;sets:number;reps:number;weight:number};
export type Workout={id:string;user_id:string;date:string;title:string;sport:'Laufen'|'Kraft'|'Athletik';steps:Step[];notes:string;revision:number;result?:Result};
export type Result={score:number;rpe:number;distance_m:number;shoe_id:string|null;notes:string;sets:string};
export type Shoe={id:string;name:string;initial_m:number;limit_m:number;archived:number;total_m:number};
export const kinds={warmup:'Einlaufen / Aufwärmen',steady:'Belastung',interval:'Intervallblock',cooldown:'Auslaufen / Cooldown',strength:'Kraftübung'};
export function newStep(kind:Step['kind']):Step{return {kind,name:'',amount:10,unit:'min',target:'',repeat:4,rest:120,restTarget:'Locker',sets:3,reps:10,weight:0};}
export function validDate(v:unknown){return typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;}
export function trainingAllowed(a:{status:string;package:string;start_date:string|null;end_date:string|null},sport:string){const now=new Date().toISOString().slice(0,10);return a.status==='active'&&(!a.start_date||a.start_date<=now)&&(!a.end_date||a.end_date>=now)&&(a.package==='Premium'||a.package==='Basic Plus'||a.package==='Basic'&&sport==='Laufen'||a.package==='Kraftplan'&&sport!=='Laufen');}
export function validateWorkout(v:Workout){if(!v||!validDate(v.date)||typeof v.title!=='string'||!v.title.trim()||v.title.length>120||!['Laufen','Kraft','Athletik'].includes(v.sport)||typeof v.notes!=='string'||v.notes.length>4000||!Array.isArray(v.steps)||!v.steps.length||v.steps.length>60)throw Error('Bitte Titel, Datum und mindestens einen Trainingsabschnitt angeben.');for(const s of v.steps){if(!s||!Object.hasOwn(kinds,s.kind)||!['min','sec','km','m','lap'].includes(s.unit)||typeof s.target!=='string'||s.target.length>200||typeof s.name!=='string'||s.name.length>150||typeof s.restTarget!=='string'||s.restTarget.length>200)throw Error('Ungültiger Trainingsabschnitt.');for(const k of ['amount','repeat','rest','sets','reps','weight'] as const)if(!Number.isFinite(s[k])||s[k]<0||s[k]>10000)throw Error('Bitte gültige Trainingswerte eintragen.');if(s.kind==='strength'&&(!s.name.trim()||!Number.isInteger(s.sets)||s.sets<1||!Number.isInteger(s.reps)||s.reps<1))throw Error('Kraftübungen benötigen Name, Sätze und Wiederholungen.');if(s.kind==='interval'&&(!Number.isInteger(s.repeat)||s.repeat<1||s.repeat>100))throw Error('Bitte 1–100 Wiederholungen angeben.');if(s.kind!=='strength'&&s.unit!=='lap'&&s.amount<=0)throw Error('Dauer oder Strecke muss grösser als null sein.');}return v;}
