import { readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const publicDir = new URL('../public/', import.meta.url);
const hashes = new Set();
for (const name of await readdir(publicDir)) {
  if (!name.endsWith('.html')) continue;
  const html = await readFile(new URL(name, publicDir), 'utf8');
  for (const [, source] of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) {
    hashes.add("'sha256-" + createHash('sha256').update(source).digest('base64') + "'");
  }
}
const headers = {
  'Content-Security-Policy': `default-src 'self'; script-src 'self' ${[...hashes].sort().join(' ')}; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src https://formsubmit.co; form-action https://formsubmit.co; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; upgrade-insecure-requests`,
  'Strict-Transport-Security': 'max-age=31536000',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
};
await writeFile(new URL('../worker/security-headers.mjs', import.meta.url), '// Generated by scripts/security-headers.mjs.\nexport const securityHeaders = ' + JSON.stringify(headers, null, 2) + ';\n');
await writeFile(new URL('_headers', publicDir), '/*\n' + Object.entries(headers).map(([name, value]) => `  ${name}: ${value}`).join('\n') + '\n');
