// Generated by scripts/security-headers.mjs.
export const securityHeaders = {
  "Content-Security-Policy": "default-src 'self'; script-src 'self' 'sha256-9Hu9GmjTiBdOnw3EvPHjeSY8aQbOU0wRpGBO6v4kcM4=' 'sha256-LRNhj6Bn3RD2VIV1g0YI0uRsBgYvn/oxiBs7ZQL6E/o=' 'sha256-YAUO5BHKEFVkAm2mZ7EurnzyI53VWFtxUIckeVIgTEc='; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'none'; form-action https://formsubmit.co; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; upgrade-insecure-requests",
  "Strict-Transport-Security": "max-age=31536000",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
  "Permissions-Policy": "camera=(), microphone=(), geolocation=()"
};
